# .air.toml
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ."
bin = "./tmp/main"
include_ext = ["go", "tmpl", "tpl"]
exclude_dir = ["assets", "tmp", "vendor", "frontend/node_modules"]

[log]
time = true
